### ISSUE TITLE
EventId duplication

### ISSUE THREAD

**Issue by Sirozha1337** [markmcdowell/NLog.Targets.ElasticSearch#141] opened 2021-05-11 11:49 UTC
When logging messages like this:
`logger.LogError(new EventId(1, "Test"), "some message")`
The following Json object gets logged in ElasticSearch:
```
{
   "level": "Error",
   "message": "some message",
   "EventId_Id": 1,
   "EventId_Name": "Test",
   "EventId": {
       "Id": 1,
       "Name": "Test"
   }
}
```
The same information about the event gets logged twice. 

Is this a bug or the intended behaviour?

**Comment by Sirozha1337** [comment] 2021-05-12 11:56
@snakefoot thanks for the quick response. I used the `ExcludedProperties` option to remove duplicated fields. 
Should I close this issue or will you close it when it gets fixed by NLog team?

**Comment by snakefoot** [comment] 2021-05-12 14:24
Closing the issue is fine, since not for this repository.


Sent from my Sony Xperia


---- Sergey Chernyaev wrote ----


@snakefoot<https://github.com/snakefoot> thanks for the quick response. I used the ExcludedProperties option to remove duplicated fields.
Should I close this issue or will you close it when it gets fixed by NLog team?

**Closed** 2021-05-12 14:59 UTC
