### ISSUE TITLE
Unable to change target URI after it is been read from NLog.config

### ISSUE THREAD

**Issue by mindisk** [markmcdowell/NLog.Targets.ElasticSearch#91] opened 2019-05-07 09:25 UTC
I am using NLog to write logs to ElasticSearch. I have defined the ElasticSearch target in the NLog.config file which looks like this:

`<target name="defaultelastictarget" xsi:type="BufferingWrapper" bufferSize="10" flushTimeout="5000><target xsi:type="ElasticSearch" uri="http://localhost">`

Now, after the NLog.config file is loaded to the LogManager, I need to programatically update Uri of this target. However, after I updated it by calling `elasticSearchTarget.Uri = "new uri"` and then calling `LogManager.ReconfigExistingLoggers()`, the log messages are not written to the ElasticSearch. It seems that the target is not reloaded and reinitialized with the new Uri. 

The only way I managed to make it work is to construct new `ElasticSearchTarget` instance for with the new Uri and completely remove the original target (defined in NLog.config) and replace with the new `ElasticSearchTarget` instance I just created.

I am not sure if I am even correctly updating Uri of  `ElasticSearchTarget` , I did not managed to find any example of how to do it. It feels a bit excessive to destroy original target and create new one just for updating a single property. 

Is this a valid issue or I was updating the Uri in the wrong way?

**Comment by markmcdowell** [comment] 2019-05-07 12:17
Hey it seems valid, it's unclear to me what `ReconfigExistingLoggers` actually does to a target. 

The uri is setup when Initialising the target so I'm assuming it's not reinitialised, which is why you don't see it change.

The Uri field is a Layout so you could just use a variable here instead of reloading.

**Comment by snakefoot** [comment] 2019-05-07 19:02
`LogManager.ReconfigExistingLoggers()` refreshes all existing NLog-Logger-objects, and applies any changes made to Logging-rules. But will also initialize **new** NLog-targets that have been added with new Logging-rules. It will NOT initialize targets that have already been initialized.

You could do something like this this in NLog.config:

```xml
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http://localhost}" />
```

Then update the `newUri` in [GDC](https://github.com/NLog/NLog/wiki/Gdc-layout-renderer), and reload the NLog-config:

```c#
NLog.GlobalDiagnosticsContext.Set("newUri", "someValue");
NLog.LogManager.Configuration = NLog.LogManager.Configuration.Reload();
```

**Comment by mindisk** [comment] 2019-05-08 07:44
I tried this approach and it did not work as expected. 
Surprisingly `ElasticSearchTarget` took the `uri` attribute as a whole string. meaning that the target's Uri property is now the entire string of `"${gdc:item=newUri:whenEmpty=localhost}"`.

**Comment by snakefoot** [comment] 2019-05-08 08:05
Are you using ver. 5.10 or ver. 6.1.0<tel:6.1.0>?


Sent from my Sony Xperia


---- Mindaugas wrote ----


I tried this approach and it did not work as expected.
Surprisingly ElasticSearchTarget took the uri attribute as a whole string. meaning that the target's Uri property is now the entire string of "${gdc:item=newUri:whenEmpty=localhost}".

**Comment by mindisk** [comment] 2019-05-08 09:21
6.1.0

**Comment by snakefoot** [comment] 2019-05-08 09:34
When looking at the Uri-property then it will not show the resolved string


You should look at the _client-field on the target, and verify if it has resolved the node correctly after reload.



Sent from my Sony Xperia


---- Mindaugas wrote ----


6.1.0

**Comment by mindisk** [comment] 2019-05-08 10:19
By following this: 
```
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=localhost}" />
```
The  `_client` field within `ElasticSearchTarget` is `null`. I  can see in the debugger that there are some `System.UriFormatException` exceptions thrown. I believe it is due to that it takes  `"${gdc:item=newUri:whenEmpty=localhost}"` as a single string and it cannot parse it as valid uri. 

It seems that NLog cannot handle `gdc` and do appropriate value substitutions for some reason.

**Comment by snakefoot** [comment] 2019-05-08 10:21
What value have you assigned to newUri?


Sent from my Sony Xperia


---- Mindaugas wrote ----


By following this:

<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=localhost}" />


The _client field within ElasticSearchTarget is null. I can see in the debugger that there are some System.UriFormatException exceptions thrown. I believe it is due to that it takes "${gdc:item=newUri:whenEmpty=localhost}" as a single string and it cannot parse it as valid uri.

It seems that NLog cannot handle gdc and do appropriate value substitutions for some reason.

**Comment by mindisk** [comment] 2019-05-08 11:02
The problem is that the Uri property in the `ElasticSearchTarget` looks like this:
```
elasticSearchTarget.Uri == "${gdc:item=newUri:whenEmpty=localhost}"
```
Therefore, whatever address I try assigning to the `newUri`, it does not work.  
The format of `newUri` is: `http://[local_ip]:9200`

**Comment by snakefoot** [comment] 2019-05-08 11:06
How do you assign this newUri address?


Pretty sure ${gdc} is working very well. When you provide a valid item-key


Sent from my Sony Xperia


---- Mindaugas wrote ----


The problem is that the Uri property in the ElasticSearchTarget looks like this:

elasticSearchTarget.Uri == "${gdc:item=newUri:whenEmpty=localhost}"


Therefore, whatever address I try assigning to the newUri, it does not work.
The format of newUri is: http://[local_ip]:9200

**Comment by mindisk** [comment] 2019-05-08 11:27
I followed given example:
```
NLog.GlobalDiagnosticsContext.Set("newUri", "http://[local_ip]:9200");
NLog.LogManager.Configuration.Reload();
```

When I use this fomat:
```
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=localhost}" />
```
I even tried to use valid localhost uri:
```
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http://localhost:9200}" />
```
The `_client` field within `ElasticSearchTarget` is not initialized before even setting the variable assignment and `System.UriFormatException` exceptions are thrown internally.


I tried to initialize the target  normally to see if exceptions are thrown. 
```
<variable name="elasticSearchUri" value="http://localhost:9200" />
<target xsi:type="ElasticSearch" uri="${elasticSearchUri}">
```
The `System.UriFormatException` exceptions were not thrown and the `_client` field within `ElasticSearchTarget` is initialized. 

The major problem is that I cannot even initialize a `ElasticSearchTarget` with not null `_client` field when I use GDC. So either NLog has some issue with parsing GDC attribute values or the ElasticSearchTarget.

**Comment by snakefoot** [comment] 2019-05-08 17:18
> A thought: Can it be that GDC is not properly working because my project does not posses NLog.xsd?

No you are wrong. Try this instead (Ensure whenEmpty-fallback has a valid Uri):

```xml
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost:9200}" />
```

```c#
NLog.GlobalDiagnosticsContext.Set("newUri", "someValue");
NLog.LogManager.Configuration = NLog.LogManager.Configuration.Reload();
```

**Comment by snakefoot** [comment] 2019-05-08 17:19
> A thought: Can it be that GDC is not properly working because my project does not posses NLog.xsd?

No you are wrong. Try this instead (Ensure whenEmpty-fallback has a valid Uri):

```xml
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost:9200}" />
```

```c#
NLog.GlobalDiagnosticsContext.Set("newUri", "someValue");
NLog.LogManager.Configuration = NLog.LogManager.Configuration.Reload();
```

**Comment by snakefoot** [comment] 2019-05-08 17:19
> @mindisk  A thought: Can it be that GDC is not properly working because my project does not posses NLog.xsd?

No you are wrong. Try this instead (Ensure whenEmpty-fallback has a valid Uri):

```xml
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost:9200}" />
```

```c#
NLog.GlobalDiagnosticsContext.Set("newUri", "someValue");
NLog.LogManager.Configuration = NLog.LogManager.Configuration.Reload();
```

**Comment by snakefoot** [comment] 2019-05-08 19:20
> @mindisk  A thought: Can it be that GDC is not properly working because my project does not posses NLog.xsd?

No you are wrong. Try this instead (Ensure whenEmpty-fallback has a valid Uri):

```xml
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost:9200}" />
```

```c#
NLog.GlobalDiagnosticsContext.Set("newUri", "http://[local_ip]:9200");
NLog.LogManager.Configuration = NLog.LogManager.Configuration.Reload();
```

P.S. Instead of returning `[local_ip]:9200`. Why not just `http://localhost:9200`?

**Comment by mindisk** [comment] 2019-05-09 10:31
The `[local_ip]:9200` thing was just an example meaning some IP on my local network. 

Anyway, your solution worked. Keep in mind to escape second colon.

In NLog.config
```
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost\:9200}">
```

In the code:
```
NLog.GlobalDiagnosticsContext.Set("newUri", http://[some_ip]:9200");
NLog.LogManager.Configuration.Reload();
```

Thank you for the help.

**Comment by mindisk** [comment] 2019-05-09 11:22
Sorry for misleading. It is not completely there yet. I forgot to disable the re-initialization of new instance of `ElasticSearchTarget`. Because of it, the new target was initialized with the new Uri.

So the current state is that GDC works fine when initializing initial target.  The Uri is `http://localhost:9200` when using GDC like this:
```
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost\:9200}">
```

However, updating `newUri` variable does not seem to work using:
```
NLog.GlobalDiagnosticsContext.Set("newUri", http://[some_ip]:9200");
NLog.LogManager.Configuration.Reload();
```
The log messages are being sent to `http://localhost:9200` and not to the new address.

**Comment by snakefoot** [comment] 2019-05-09 11:35
You are doing the reload the wrong way. Look at my code. You are missing the assignment


Sent from my Sony Xperia


---- Mindaugas wrote ----


Sorry for misleading. It is not completely there yet. I forgot to disable the re-initialization of new instance of ElasticSearchTarget. Because of it, the new target was initialized with the new Uri.

So the current state is that GDC works fine when initializing initial target. The Uri is http://localhost:9200 when using GDC like this:

<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost\:9200}">


However, updating newUri variable does not seem to work using:

NLog.GlobalDiagnosticsContext.Set("newUri", http://[some_ip]:9200");
NLog.LogManager.Configuration.Reload();


The log messages are being sent to http://localhost:9200 and not to the new address.

**Comment by mindisk** [comment] 2019-05-09 13:17
You're right. It finally works. 

All in all, this is the sollution:
```
<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost\:9200}">
```
and
```
NLog.GlobalDiagnosticsContext.Set("newUri", "http://[local_ip]:9200");
NLog.LogManager.Configuration = NLog.LogManager.Configuration.Reload();
```

The side effect is that all variable assignments and other target configurations that have been done before programmatically fall back to their initial values that were defined in NLog.config. As I witnessed this approach does not retain variable assignments.

**Closed** 2019-05-09 13:17 UTC

**Comment by snakefoot** [comment] 2019-05-09 14:05
The issue with reset of variables on reload. Is the reason why I'm suggesting the use of GDC.


Sent from my Sony Xperia


---- Mindaugas wrote ----


You're right. It finally works.

All in all, this is the sollution:

<target xsi:type="ElasticSearch" uri="${gdc:item=newUri:whenEmpty=http\://localhost\:9200}">


and

NLog.GlobalDiagnosticsContext.Set("newUri", "http://[local_ip]:9200");
NLog.LogManager.Configuration = NLog.LogManager.Configuration.Reload();


The side effect is that all variable assignments and other target configurations that have been done before programmatically fall back to their initial values that were defined in NLog.config. As I witnessed this approach does not retain variable assignments.

**Comment by snakefoot** [comment] 2019-05-09 17:41
@mindisk I have now created this wiki-page after seeing all the trouble you have been through:

https://github.com/NLog/NLog/wiki/Dependency-injection-with-NLog#initialize-nlog-configuration

**Comment by mindisk** [comment] 2019-05-14 11:49
Appreciate it. Thank you very much!
